### ISSUE TITLE
Add netlink command support

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#186]
To allow userspace path management, both the netlink path managment events (b911c97c7dc7) and commands are required. Right now, mptcpd can receive events but not control which subflows are opened or closed. The command API should match what was implemented in [mptcp_trunk](https://github.com/multipath-tcp/mptcp/tree/mptcp_trunk).

This requires:
- Make each socket configurable for either in-kernel or userspace path management (or only configure per-namespace?)
- Configure default path management type (in-kernel or userspace), per namespace
- Bypass the in-kernel path manager for userspace-managed sockets
- Parse and validate netlink commands

**Comment by fw-strlen** [comment]
The mptcp_trunk command types needed for this are:
MPTCP_CMD_ANNOUNCE = 4, 
MPTCP_CMD_REMOVE = 5,
MPTCP_CMD_SUB_CREATE = 8,
MPTCP_CMD_SUB_DESTROY = 9,

Unfortunately, ANNOUNCE/REMOVE conflict with 
MPTCP_PM_CMD_FLUSH_ADDRS and MPTCP_PM_CMD_SET_LIMITS.
CREATE/DESTROY work because those index numbers are still available.

One way would be to overload these two and make their behaviour dependant on the
presented attributes.  But that just brings us to the next problem:
MPTCP_ATTR_TOKEN (first supported attribute) collides with 
MPTCP_PM_ATTR_ADDR. IOW, we can't even add the required netlink policies for them
(they don't have any at the moment, they are only used to send events, not to receive commands).

So, as far as i can see that leaves three options:
1. make a different API, using new MPTCP_PM_CMD_ANNOUNCE and so on, and add new attributes
2. make a new genl subsystem for mptcp
3. break both ABI and API, unify everyhing and bump MPTCP_PM_VER.
I think 1 is the only realistic option though. 2) appears rather arkward due to duplication and 3 is only mentioned for completeness.

**Comment by mjmartineau** [comment]
@fw-strlen: Any thoughts on "option 4": keep the symbolic command names and attributes, and use different index numbers for everything upstream.

I had been thinking we were not concerned about binary compatibility with the fork, just reusing the API design.

**Comment by mjmartineau** [comment]
Maybe my option 4 is what @fw-strlen was saying with option 1, other than the exact names - so a chance that we're in agreement there

**Comment by fw-strlen** [comment]
> @fw-strlen: Any thoughts on "option 4": keep the symbolic command names and attributes, and use different index numbers for everything upstream.

Would create failing/oddly-acting binary in ase package is built with the 'wrong' headers.
If thats okay, then sure, this could be done.
 
> I had been thinking we were not concerned about binary compatibility with the fork, just reusing the API design.

I thought it was cleaner to re-do everything, the API would look pretty similar though.

**Comment by matttbe** [comment]
@mjmartineau raised a point at the last meeting: for ADD_ADDR, we need to handle ECHO ones

- for the moment, we only handle the retransmission of one ADD_ADDR:
  - either we have a new events to tell the userspace when to send the next one (when the echo has been received)
  - or the userspace is in charge of the retransmissions
  - or we keep a list of ADD_ADDR to retransmit (can be done as a second step)
- We decided to let the kernel managing that: no need to add a new event for that
- (if needed, managing a list of ADD_ADDR can be done later)

**Comment by matttbe** [comment]
Can be closed now thanks to @kmaloor patches:

New patches for t/upstream:
- c2dcdbadfac0: mptcp: allow ADD_ADDR reissuance by userspace PMs
- 26c71440e307: mptcp: handle local addrs announced by userspace PMs
- 5a865082c99a: mptcp: read attributes of addr entries managed by userspace PMs
- 899ec4b7d092: mptcp: netlink: split mptcp_pm_parse_addr into two functions
- 37d4d520025a: mptcp: netlink: Add MPTCP_PM_CMD_ANNOUNCE
- 90e75a0f1e7a: selftests: mptcp: support MPTCP_PM_CMD_ANNOUNCE
- 151abf946ec6: mptcp: netlink: Add MPTCP_PM_CMD_REMOVE
- 961b8d01cd00: selftests: mptcp: support MPTCP_PM_CMD_REMOVE
- 68f10488da73: mptcp: netlink: allow userspace-driven subflow establishment
- 04de6ee0fd99: selftests: mptcp: support MPTCP_PM_CMD_SUBFLOW_CREATE
- 337354cbefde: selftests: mptcp: support MPTCP_PM_CMD_SUBFLOW_DESTROY
- feac5b7157cd: selftests: mptcp: capture netlink events
- 802a0fcee8de: selftests: mptcp: create listeners to receive MPJs
- 7a589792c590: selftests: mptcp: functional tests for the userspace PM type
- Results: dd31cb34f82b..f0428dbd45eb (export)

And an extra fix for the CI:

- 6505be1e8a40: Squash to "mptcp: handle local addrs announced by userspace PMs"
- (no co-dev for that)
- 66af7c7950d4: mptcp: remove dup mptcp_pm_addr_entry
- c14d95c1413b: conflict in t/mptcp-netlink-allow-userspace-driven-subflow-establishment
- Results: f0428dbd45eb..4fa4540bfc5e (export)
