### ISSUE TITLE
MPTCP v5.13 kernel compilation Fail to load/boot 

### ISSUE THREAD

**Issue by sdntechforum** [multipath-tcp/mptcp_net-next#212]
Hi All,

I have successfully complied the v5.13 kernel and set this to default. Please see the logs below. However when I reboot the device, I.  get the error -  ../grub-core/loader/efi/limux.c:119:can't allocate initrd
Then Kernel Panic ad just sits there. Any suggestions how can I load new kernel to boot. 

##################
[asingh47@snuc-desktop x86_64]$ ls -l
total 1139208
-rw-rw-r--. 1 asingh47 asingh47 994963240 Jun 21 10:11 kernel-5.13.0_rc6+-1.x86_64.rpm
-rw-rw-r--. 1 asingh47 asingh47 170145408 Jun 21 10:11 kernel-devel-5.13.0_rc6+-1.x86_64.rpm
-rw-rw-r--. 1 asingh47 asingh47   1434392 Jun 21 10:11 kernel-headers-5.13.0_rc6+-1.x86_64.rpm
[asingh47@snuc-desktop x86_64]$

asingh47@snuc-desktop etc]$ sudo grubby --info="/boot/vmlinuz-5.13.0-rc6+"
index=0
kernel="/boot/vmlinuz-5.13.0-rc6+"
args="ro crashkernel=auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet $tuned_params"
root="/dev/mapper/cl-root"
initrd="/boot/initramfs-5.13.0-rc6+.img $tuned_initrd"
title="CentOS Linux (5.13.0-rc6+) 8"
id="a55c15ef2a3346cc8d76be9c2fb804c9-5.13.0-rc6+"

################

Thanks,

Amit

**Comment by matttbe** [comment]
Hi Amit,

Thank you for using MPTCP but I'm not sure we will be able to help you here as this error is not related to MPTCP.

From what I see, the 'initrd' is somehow too big. The RPM you have produced are huge, no? Almost 1GB from what I see.
Is it because all kernel options have been enabled?
In this case, I guess you need "a lot" of resources to start it. If you use a VM, you can re-dimension it but maybe best to use a lighter kernel configuration (`x86_64_defconfig` and enable what you need need or copy the one of your distribution as a base).

If needed, many distributions also build recent kernels and MPTCP is usually enabled by default (if not, please tell us/them). e.g.
- for Fedora, it is in Raw Hide repo or [this one](https://fedoraproject.org/wiki/Kernel_Vanilla_Repositories).
- for Ubuntu, it is on [a PPA](https://kernel.ubuntu.com/~kernel-ppa/mainline/)
- etc.

I hope you don't mind if I close this ticket as it is not related to MPTCP.
