### ISSUE TITLE
Kernel Compilation failed 

### ISSUE THREAD

**Issue by sdntechforum** [multipath-tcp/mptcp_net-next#232]
Hi All,

Kernel compilation is failing with following error -

error: 'EM_RISCV' undeclared (first use in this function); did you mean 'EM_CRIS'?

Anyone seen this before ?

Thanks,
Amit

**Comment by sdntechforum** [comment]
Can someone please suggest a working code in mptcp_net_next branch and how to download that ? I am looking to run mPTCP version 1 only.

**Comment by dcaratti** [comment]
hello @sdntechforum can you try appying  [upstream commit fe7118f4742f ](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?h=next-20210924&id=fe7118f4742f8c26e532c63bb498283b73e24d7d) ? that should fix your error.

**Comment by matttbe** [comment]
The upstream commit is in [Linus' tree](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/scripts/sorttable.c?id=d09c38726c78effaf910a1e3f31e247b5b031d56) and I expect to be very soon in net-next, probably tomorrow in our `export` branch.
Because it is not related to MPTCP, I guess we can close this issue.

Commit: d09c38726c78effaf910a1e3f31e247b5b031d56
