### ISSUE TITLE
Receiver key overwritten in a packet with mpc+data

### ISSUE THREAD

**Issue by spoorva** [multipath-tcp/mptcp_net-next#233]
when creating an outbound packet with mpc and data set, it was observed that the receiver key's value is not set when checksum checking is enabled. This could be due to restructuring of struct mptcp_out_options .

**Comment by pabeni** [comment]
Indeed! this is very likely caused by:

```
commit d7b269083786dca3b1b0141bde6cea834062b691
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Tue Aug 24 16:26:14 2021 -0700

    mptcp: shrink mptcp_out_options struct
```

After that commit rcvr_key share the same memory of ext_copy inside the out options struct. mpc+data uses both rcvr_key and ext_copy. With no csum, the only ext_copy field used is data_len, and that last does not overlap with any MPC data. With csum enabled, we additionally touch data_seq, subflow_seq and the csum itself, corrupting the key value.

A good solution should not increase the mptcp_out_options struct size. e.g. we can add to the anonymous struct containing the keys the needed info for mpc+data+csum, and use that storage instead of ext_copy.
