### ISSUE TITLE
Compilation problem with a 4.14.y kernel

### ISSUE THREAD

**Issue by eackkk** [multipath-tcp/mptcp_net-next#249]
Hi, does mptcp support arm64 architecture? I downloaded the mptcp code incorporated into linux 4.14.* and tried to compile it into aarch64 architecture, but I found that there is no in the .config file:
CONFIG_MPTCP=y
CONFIG_INET_MPTCP_DIAG=y
CONFIG_MPTCP_IPV6=y
only:
CONFIG_DEFAULT_MPTCP_PM="default"
There are a small number of mptcp related strings in the compiled vmlinux, but I am not sure whether the .config display is normal

**Comment by eackkk** [comment]
When I compile menuconfig with arm64, no MPTCP related options are found

**Comment by matttbe** [comment]
Hi,

As detailed in our [Wiki](https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog), MPTCP is only supported in the mainline Linux since v5.6 (with very limited features).

If you want to have MPTCP support on your 4.14 kernel and you cannot easily upgrade to the v5.15 one, you can modify your kernel using patches from this out-of-tree project: https://github.com/multipath-tcp/mptcp

**Comment by matttbe** [comment]
Because I don't think we can do anything to help here with kernels older than v5.6, I hope you don't mind if I close this ticket.
