### ISSUE TITLE
csum: bad encoding 

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#275]
the current encoding of the csum field in the MPTCP DSS option is wrong: the __sum value is converted to BE, inverting the byte order on LE arches, which is not expected.

@darkwrat confirmed the above causes interoperability issues between hosts with different endianess.

The solution is problematic WRT backward compatibility, but we don't have many options

**Comment by mjmartineau** [comment]
Some context from the mailing list:

Patch fixing little-endian csum byte order: https://lore.kernel.org/mptcp/595f104803a212df58db6d20f84947325b33a9d6.1652196378.git.pabeni@redhat.com/

Patch allowing fallback instead of connection reset on first checksum failure: https://lore.kernel.org/mptcp/20220511235137.431538-1-mathew.j.martineau@linux.intel.com/

Both of those are in the export-net branch now.

Some mixed-endian testing from @darkwrat: https://lore.kernel.org/mptcp/3c85fe48-69fe-0655-2146-a4424e02f185@internet.ru/

**Comment by mjmartineau** [comment]
I also confirmed interop of the fixed code with the mptcp_trunk kernel, both running on little-endian machines.

**Comment by matttbe** [comment]
Patches have been applied in our tree and already in -net (soon in Linus' tree)
