### ISSUE TITLE
pm_type in upstream implementation of mptcp

### ISSUE THREAD

**Issue by abhinaba-fbr** [multipath-tcp/mptcp_net-next#306]
Hi,
I was going through the previous closed tickets regarding the path manager. So far I understood that, the support for the path manager in kernel (like in v0 implementation) has been moved from kernel to userspace. Is my understanding correct in this regard? 

And there exists a new config variable called **pm_type** which has two settings (0 means 'in-kernel' and 1 means 'userspace'). What do you mean here by the term in-kernel? Does that mean v1 still implements some part of the path management in the kernel itself?

**Comment by matttbe** [comment]
Hi,

> like in v0 implementation

Be careful that when we talk about v0/v1, it is about the MPTCP protocol (RFC 6824 vs 8684), not the Linux kernel implementation (out of tree vs upstream): [Upstream vs out-of-tree implementations](https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations)

In the out-of-tree implementation, we also have the possibility to control the path manager per connection via userspace.

> the support for the path manager in kernel has been moved from kernel to userspace. Is my understanding correct in this regard?

Not really because we currently have 2 different modes:
- one "in-kernel" path-manager trying to cover most use-cases and controllable with `ip mptcp` (but also Network Manager 1.40+ and mptcpd)
- and one to cover more specific use cases, controlled per connection via userspace, e.g. with mptcpd.

> And there exists a new config variable called pm_type which has two settings (0 means 'in-kernel' and 1 means 'userspace'). What do you mean here by the term in-kernel? 

See #300 for more details.

Compared to the out-of-tree implementation, instead of using all available IP to create a fullmesh by default (when 'fullmesh' PM is picked), the user has to provide which IPs to use. But this can be automated with Network Manager and mptcpd.

Does it answer your questions? Feel free to close the ticket if yes.

**Comment by abhinaba-fbr** [comment]
Thanks a lot @matttbe for your reply.

Your comment solves my doubt. 
I am closing the ticket.
