### ISSUE TITLE
Very noisy `addr_signal error`

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#378]
One of my syzkaller scripts triggers an endless list of logs because of `addr_signal error`.

Maybe worth rate-limiting that ??

**Comment by cpaasch** [comment]
```
[   29.812885] MPTCP: addr_signal error, rm_addr=4
[   29.814039] MPTCP: addr_signal error, rm_addr=4
[   29.815000] MPTCP: addr_signal error, rm_addr=4
[   29.816125] MPTCP: addr_signal error, rm_addr=4
```

**Comment by matttbe** [comment]
Good idea, I think we can consider this as a bug instead of a new feature.

The message has been introduced in commit 42842a425ad6d1ef1087b63486879a6d54b26893 ("_mptcp: drop rm_addr_signal flag_") but maybe it is due to the userspace PM?

Do you know which PM was in used when you had the message? (a call trace maybe?)

**Comment by matttbe** [comment]
From the last meeting:

- should probably be tracked by a MIB counter instead
- can happen when:
  - we try to remove multiple addresses but we only do once at a time
  - we suppose it is only happening with the in-kernel PM
  - the RM_ADDR will all be sent at some points
- we should track the error but in a less impacting way
