### ISSUE TITLE
Problem attempting to use all my interfaces (subflows) 

### ISSUE THREAD

**Issue by IhebZanina** [multipath-tcp/mptcp_net-next#392]
Hello, 

I got MPTCP coming with Linux 5.19.0-38-generic Kernel. 
In my 2 laptops I have 3 interfaces (Ethernet, WLAN, 4G network using "USRP B210").
The routing is fine and both laptops can communicate through the 3 interfaces. 
I am trying to use 1 laptop as a server and the other as a client to download a big file using all the available subflows (3 interfaces), but I can use just 2 interfaces in a row, `(Ethernet and WLAN) or (WLAN and 4G)`.

Is that how the scheduler works? I am aware that the default scheduler in the upstream version is BPF_FIRST and by definition this scheduler should use all the available interfaces, which always picks the first subflow to send data. It's a sample of
MPTCP BPF scheduler implementations.

### MPTCP Client Configuration:
ip mptcp limits set add_addr_accepted 3 subflow 3

### MPTCP Server Configuration:
ip mptcp limits set add_addr_accepted 3 subflow 3
ip mptcp endpoint add <WLAN IP address> dev <WLAN interface name> subflow signal

**Comment by matttbe** [comment]
Hello,

> The routing is fine and both laptops can communicate through the 3 interfaces.

What kind of routing did you put in place?
Did you add an `ip rule from <IP> table <TABLE>` and `ip route add default via <GW IP> dev <DEVICE> table <TABLE>` per address you want to use? For more details about that, see this: https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting

Please share text and not screenshots.

> I am trying to use 1 laptop as a server and the other as a client to download a big file using all the available subflows (3 interfaces), but I can use just 2 interfaces in a row, (Ethernet and WLAN) or (WLAN and 4G).

Sorry, I'm not sure to understand: what's the expected behaviour and what do you have now?
Do you want to use 3 interfaces at the same time but it only works with two?

> Is that how the scheduler works? I am aware that the default scheduler in the upstream version is BPF_FIRST and by definition this scheduler should use all the available interfaces, which always picks the first subflow to send data. It's a sample of
MPTCP BPF scheduler implementations.

The BPF packet scheduler work is in progress, it is not in any stable version (so not in 5.19). For more details: https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog
We recommend to use at least the latest stable version (6.2) (or latest LTS: 6.1).

Regarding MPTCP: you have the path manager that is in charge of managing subflows (= paths), e.g. creating new paths, etc.
Then the packet scheduler, to select the path where the data will be sent to.

If you don't have the good amount of paths (see with `ss` or `tcpdump`), you need to look at the path manager (likely `ip mptcp endpoint`)

What's the list of endpoints per host (please share text and not screenshots)?
Did you add all additional endpoints on both the client side (with the `subflow` flag`) and on the server side (`signal` flag)?
Or did you use `mptcpd` to do that for you? (maybe it added too many endpoints)

**Comment by IhebZanina** [comment]
Hallo, 



> What kind of routing did you put in place?
> Did you add an `ip rule from <IP> table <TABLE>` and `ip route add default via <GW IP> dev <DEVICE> table <TABLE>` per address you want to use? For more details about that, see this: https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting

No, I am actually using the  **Automatic Configuration** _section 1_ `Using the configuration scripts (Ubuntu/Debian-based systems)`. And I guess I don't need the routing configuration because in my scenario it should be configured automatically. 

Picture this: 

- Interface 1: Two laptops connected through Ethernet `RJ45` to a switch to a router to the internet, in turn they get there IP addresses (Same LAN1) and Gateways somewhere from the _DHCP_ server.
- Interface 2: Two laptops connected through WIFI  to an access point  to a router to the internet, in turn they get there IP addresses (Same LAN2) and Gateways somewhere from the _DHCP_ server.
- Interface 3: Two laptops connected through 4G network via "USRP B210" cards, in turn 1 laptop act as a 4G UE and the second laptop as a 4G e-NodeB, in turn the first laptop get the IP address (Same LAN3) and Gateway from the e-NodeB _DHCP_ server when he got connected to the "USRP B210" card.



> Sorry, I'm not sure to understand: what's the expected behaviour and what do you have now?
> Do you want to use 3 interfaces at the same time but it only works with two?

Yes, I can use just 2 interfaces in a row, `(Ethernet and WLAN)` or `(WLAN and 4G)`.

> Regarding MPTCP: you have the path manager that is in charge of managing subflows (= paths), e.g. creating new paths, etc.
> Then the packet scheduler, to select the path where the data will be sent to.

What's the name of the default current packet scheduler I am using in the 5.19 version. Is it the Round Robin? Is it open source? Can I change the source code of that scheduler in order to get the best scheduler configuration based on my variant scenarios?  Could you elaborate, Thank you.

> Please share text and not screenshots.

!sure, the description has been edited.

> Did you add all additional endpoints on both the client side (with the `subflow` flag`) and on the server side (`signal`flag)?`

No, I just added the **3** subflows just in the server side with the command:
`ip mptcp endpoint add <Interface IP> dev <Interface name> subflow signal `
with the `ip mptcp limits set add_addr_accepted 3 subflow 3` in the **server laptop and the client laptop.** 


> `Or did you use`mptcpd` to do that for you? (maybe it added too many endpoints)

Also I am using the mptcpd To run in the server: `mptcpize run python3 -m http.server 8000`
and in the client:   `mptcpize run wget <any server interface ip address>:8000/<file location>`

With this I am able to use just 2 interfaces in a row as mentioned. 
Am I missing something?

**Comment by matttbe** [comment]
> Hallo,
> 
> > What kind of routing did you put in place?
> > Did you add an `ip rule from <IP> table <TABLE>` and `ip route add default via <GW IP> dev <DEVICE> table <TABLE>` per address you want to use? For more details about that, see this: https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting
> 
> No, I am actually using the **Automatic Configuration** _section 1_ `Using the configuration scripts (Ubuntu/Debian-based systems)`. And I guess I don't need the routing configuration because in my scenario it should be configured automatically.
> 
> Picture this:
> 
>     * Interface 1: Two laptops connected through Ethernet `RJ45` to a switch to a router to the internet, in turn they get there IP addresses (Same LAN1) and Gateways somewhere from the _DHCP_ server.
> 
>     * Interface 2: Two laptops connected through WIFI  to an access point  to a router to the internet, in turn they get there IP addresses (Same LAN2) and Gateways somewhere from the _DHCP_ server.
> 
>     * Interface 3: Two laptops connected through 4G network via "USRP B210" cards, in turn 1 laptop act as a 4G UE and the second laptop as a 4G e-NodeB, in turn the first laptop get the IP address (Same LAN3) and Gateway from the e-NodeB _DHCP_ server when he got connected to the "USRP B210" card.

I'm not sure we are talking about the same thing. When we ask "did you configure the routing" is: _if the kernel tries to send traffic forcing the source IP of one interface, will it be routed_.

If you have direct connections between your client and server (LAN), you don't need anything else. I don't know if the automatic scripts are still running. You can check with a command like to check if it will be routed through the correct device:

```
ip route get from <IP of one device>
```

(or checks the `ip rule` that have been set)

> > Sorry, I'm not sure to understand: what's the expected behaviour and what do you have now?
> > Do you want to use 3 interfaces at the same time but it only works with two?
> 
> Yes, I can use just 2 interfaces in a row, `(Ethernet and WLAN)` or `(WLAN and 4G)`.

I guess the path manager didn't create a third path. Did you check how many paths were created? Did you try to increase the limits? Did you add endpoints for each public address you want to use on both the client and the server?

* `ip mptcp endpoint`
* `ip mptcp limits`
* `ip rule`
* `ss -Menita` → with some connections ongoing

> > Regarding MPTCP: you have the path manager that is in charge of managing subflows (= paths), e.g. creating new paths, etc.
> > Then the packet scheduler, to select the path where the data will be sent to.
> 
> What's the name of the default current packet scheduler I am using in the 5.19 version. Is it the Round Robin? Is it open source? Can I change the source code of that scheduler in order to get the best scheduler configuration based on my variant scenarios? Could you elaborate, Thank you.

Only one packet scheduler in v5.19, open-source, no BPF. You can modify it, patches welcome.

But in your case, I guess you have an issue with the path manager if you only have 2 subflows instead of 3.

> > Please share text and not screenshots.
> 
> !sure, the description has been edited.

Thanks!

> > Did you add all additional endpoints on both the client side (with the `subflow` flag`) and on the server side (`signal`flag)?`
> 
> No, I just added the **3** subflows just in the server side with the command: `ip mptcp endpoint add <Interface IP> dev <Interface name> subflow signal ` with the `ip mptcp limits set add_addr_accepted 3 subflow 3` in the **server laptop and the client laptop.**

Please add endpoints on the client side as well and increase limits: maybe the PM tries to use one path which is blocked for some reasons and it cannot use more addresses.

> > `Or did you use`mptcpd` to do that for you? (maybe it added too many endpoints)
> 
> Also I am using the mptcpd To run in the server: `mptcpize run python3 -m http.server 8000` and in the client: `mptcpize run wget <any server interface ip address>:8000/<file location>`
> 
> With this I am able to use just 2 interfaces in a row as mentioned. Am I missing something?

Did you install `mptcpd` or just `mptcpize`

```
sudo systemctl status mptcp
```

**Comment by matttbe** [comment]
I suggest to close this old ticket. Feel free to re-open it and provide answers to my previous questions if you still have the issue.
