### ISSUE TITLE
Backup function in BPF schedulers

### ISSUE THREAD

**Issue by AlejandraOliver** [multipath-tcp/mptcp_net-next#393]
Hi, I was wondering if BPF schedulers will soon have a backup function, ie:
if I have three interfaces (one is to make the connection to the other machine, another one is declared as subflow and the last one as backup). If the active interface goes down, the second one (subflow) should be activated and if this one also goes down, the backup interface should be activated to transmit and receive the data.

Right now, I am trying with the different schedulers (bpf_rr, bpf_red, bpf_first, bpf_bkup) and even with the default, and in none of them this happens, so I imagine that they are still in process and this function is not yet incorporated. Is it so?

Thanks!!

**Comment by matttbe** [comment]
Hi @AlejandraOliver 

The BPF packet schedulers work is on old for the moment because there are some API changes that are required, see #350 and #75

Clearly, the demo schedulers from the BPF selftests don't implement all required features, waiting for someone to add them. In theory, the `bpf_bkup` one should only send data to the non backup ones.

**Comment by AlejandraOliver** [comment]
Ok, Thanks!!
