### ISSUE TITLE
Question: MPTCP with GStreamer

### ISSUE THREAD

**Issue by Monika-Research** [multipath-tcp/mptcp_net-next#405]
Hi Matt,

Hope you are doing well!

I would like to mptcpize the Gstreamer code which streams voice over TCP. Is it possible to do so?
In case, if it is not, using an out of tree implementation of MPTCP will do it automatically?

Please comment on this.

Thanks
Monika

**Comment by matttbe** [comment]
Hi Monika,

Thank you, I hope you are doing good as well!

> I would like to mptcpize the Gstreamer code which streams voice over TCP. Is it possible to do so?

`mptcpize <run command> | <enable service>` should force any program using a libC (generally most apps except the ones in Go) to create MPTCP sockets instead of TCP ones. So it should work I suppose (to be checked with `ss -Ma` (and/or `/proc/net/protocols` on >=v6.3)).

If not, it is either because you didn't force the right service (e.g. a daemon?) to use MPTCP or there is a bug that needs to be fixed.

**Comment by Monika-Research** [comment]
Hi Matt,

I am able to mptcpize gstreamer. Thank you.

Thanks,
Monika
