### ISSUE TITLE
when using openvpn in tcp with dco, we have a bug

### ISSUE THREAD

**Issue by KaleiRo** [multipath-tcp/mptcp_net-next#479]
Hi,

According to ovpn-dco github, we contact you for a problem when using 6.1 kernel with multiple wan with mptcp, openvpn latest version from official repo, and latest openvpn dco module.

When using TCP protocol in openvpn, we have this error from the DCO module : 

dco_new_peer: netlink reports error (-3): Bad socket
dco_new_peer: failed to send netlink message: Socket operation on non-socket (-88)
Cannot add peer to DCO for xxxx/123.123.123.123:12345: Socket operation on non-socket (-88)

we think netlink socket that was maybe closed or messed up and while mptcp is mostly transparent to user space application, the transparency might not be there for a kernel module like ovpn-dco. So this has been probably not really tested/implementend yet.

can you help to understand what's the problem and found a solution ?

**Comment by matttbe** [comment]
Hi @Kalimeiro 

> According to ovpn-dco github

I guess this is linked to this issue, right? https://github.com/OpenVPN/ovpn-dco/issues/60

I didn't know what was DCO, it looks like an out-of-tree kernel modules. MPTCP is transparent for the userspace, probably not with what they do in kernelspace. I guess the kernel module will need to be adapted to support MPTCP.

>  6.1 kernel with multiple wan with mptcp, openvpn latest version from official repo, and latest openvpn dco module.

It is not clear to me what you did to have OpenVPN using MPTCP. Can you explain a bit please? Did you use `mptcpize` and changed OpenVPN config to use TCP instead of UDP?
Or do you have issues with MPTCP connections inside a UDP tunnel?

I don't think the MPTCP kernel code needs to be adapted, probably more the OpenVPN DCO module. I guess it should help if you provide them more details about your setup: how you start OpenVPN, what's your OpenVPN configuration, how you configured MPTCP, etc.

**Comment by matttbe** [comment]
Hi @Kalimeiro

What configuration are you using?
I guess it is best to continue the discussion on the ovpn-dco ticket you created, no?

**Comment by KaleiRo** [comment]
Hello, i'm so sorry for late response, the problem is only with OpenMPTCProuter instance, it using MPTCP NEXT kernel based on OpenWRT, but I have abandoned OpenMPTCProuter for several weeks/months due to major flaws in its development.
