### ISSUE TITLE
allow 'force to MPTCP' mode: BPF

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#79]
Force to use MPTCP instead of TCP without modifying userspace apps.

From Mat in #18 :

> We don't have a suitable eBPF hook yet. We've discussed adding BPF_CGROUP_SOCKET to allow per-cgroup override of proto in the socket() call.

It can be interesting to do that with BPF because the userspace app `mptcpize` (`LD_PRELOAD` technique) because the latter has some limitations:
- it doesn't work if the application is not using libc (e.g. GoLang apps)
- in some envs, it might not be easy to set env vars / change the way apps are launched, e.g. on Android
- mptcpize needs to be launched with all apps that want MPTCP: we could have more control from BPF to enable MPTCP only for some apps or all the ones of a netns or a cgroup, etc.
- it is not in BPF, we cannot talk about it at netdev conf (:-D)

Even if mptcpize can help a lot, being able to do the modification in BPF can help in some other cases.

**Comment by nrybowski** [comment]
The earliest BPF hook in the socket life is indeed already [too late](https://elixir.bootlin.com/linux/v5.8-rc7/source/net/ipv4/af_inet.c#L388).

We may have a BPF program like this (which is very similar to [this solution](https://github.com/multipath-tcp/mptcp_net-next/issues/18#issuecomment-650529642)) : 
```
SEC("kprobe/__sys_socket")
int mptcpify(struct pt_regs *ctx) 
{
	int family = ctx->rdi, type = ctx->rsi, protocol = ctx->rdx;

	if (family == AF_INET && type == SOCK_STREAM && protocol == IPPROTO_IP) { 
		ctx->rdx = IPPROTO_MPTCP;
	}

	return 0;
}
```
but there are multiple issues. Among other : 

- In BPF, the context of the kprobes is not writable so `ctx->rdx = IPPROTO_MPTCP` will fail. We cannot use [`bpf_probe_write_user`](https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/bpf.h#L1392) since it's the kernel address space.

  - We may add a new helper `bpf_probe_write_kernel` but it seems [it isn't expected](https://www.kernel.org/doc/html/latest/bpf/bpf_design_QA.html#q-can-bpf-overwrite-arbitrary-kernel-memory).
  - We may create a new BPF program type giving writable access to the kprobe context [like this](https://lore.kernel.org/patchwork/cover/1066443/) but it leads to the next issue : 

- It does not allow per-cgroup control like expected.

  - We may create a new BPF program type allowing per-cgroup syscall context overriding but it will require some heavy work.

If kprobe (but without BPF) is the way to go, we may write an MPTCP submodule (see `samples/kprobes/kprobe_example.c`, https://lwn.net/Articles/132196/ and https://www.kernel.org/doc/Documentation/kprobes.txt) enabling system wide `__sys_socket` context rewrite.

We may also rewrite the context of `inet_create` rather than the one of `__sys_socket` to avoid the overhead of filtering unrelated socket creation (that is, not `TCP` ones). For example : 
```
SEC("kprobe/inet_create")
int mptcpify(struct pt_regs *ctx)
{
	int protocol = ctx->rdx, kern = ctx->rcx;
	struct socket *sock = (struct socket*) ctx->rsi;

	short type;
	bpf_probe_read_kernel(&type, sizeof(short), &sock->type);

	if (protocol == IPPROTO_IP && type == SOCK_STREAM && !kern) {
		ctx->rcx = IPPROTO_MPTCP;
	}
	
	return 0;
}
```

**Comment by matttbe** [comment]
@geliangtang added this new feature (thanks!), it is in net-next:

https://patchwork.kernel.org/project/netdevbpf/list/?series=776455&archive=both&state=*

  - [bpf-next,v14,1/4] bpf: Add update_socket_protocol hook
    https://git.kernel.org/bpf/bpf-next/c/0dd061a6a115
  - [bpf-next,v14,2/4] selftests/bpf: Add two mptcp netns helpers
    https://git.kernel.org/bpf/bpf-next/c/97c9c652089b
  - [bpf-next,v14,3/4] selftests/bpf: Fix error checks of mptcp open_and_load
    https://git.kernel.org/bpf/bpf-next/c/207746550262
  - [bpf-next,v14,4/4] selftests/bpf: Add mptcpify test
    https://git.kernel.org/bpf/bpf-next/c/ddba122428a7
